apiVersion: batch/v1
kind: Job
metadata:
  name: taxi-rides-outlier-detection-job
  namespace: default
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: taxi-rides-outlier-detection
        image: ghcr.io/s2410929034/taxi-rides-outlier-detection:1.0.2
        imagePullPolicy: IfNotPresent
        command: ["detect-taxi-ride-outliers", "/data"]
        volumeMounts:
        - name: local-folder
          mountPath: /data
      volumes:
      - name: local-folder
        hostPath:
          path: /mnt/c/Users/jonas/source/devops/ais-taxi-rides-g1/work
      restartPolicy: OnFailure
